# Deep Learning for Computer Vision # Week1
## Basics python
**Instructor: Dr. Phuriwat Worrawichaipat, Silpakorn University**

Topic: Basic Python & numpy

ไฟล์นี้จะเป็นไฟล์ที่ใช้สาธิตการเขียนภาษาไพธอน โดยจุดประสงค์หลักคือให้นศ.ที่ทั้งมีและไม่มีประสบการณ์การโค้ดภาษาไพธอนได้ทบทวนและเรียนรู้วิธีการเขียนโค้ด
เนื่องด้วยภาษา C และ Java ที่เรียนมานั้นมี Syntax ที่จำเพาะแต่ Python นั้นมี Syntax ที่แตกต่างออกไป(เกือบจะสิ้นเชิง)

ไฟล์นี้จะแสดงตัวอย่างของกระบวนการหลักๆที่จำเป็น(Logic)ที่เขียนโดยภาษาไพธอน ตย. การประกาศตัวแปร ชนิดตัวแปร เงื่อนไข loop หรือ opertor พิเศษต่างๆ
ให้ผู้อ่านทำความเข้าใจกับตัวคำสั่งและ Output นั้นๆ

## Variable

ตัวอย่างการประกาศตัวแปรชนิดต่าง ๆ เช่น จำนวนเต็ม ```decimal``` ```List``` ```Tuple``` ```Dictionary``` และการแสดงผลด้วยคำสั่ง ```print()``` รวมถึงการใช้ ```len()``` เพื่อนับจำนวนสมาชิกในลิสต์

In [1]:
# numbers
a = 10
b = 0.10

# List
c = ["str", 1, 2, 3, 4]
d = [0, 1, "c"]

# tuple
coor = (4, 4)

# Dictionary
contact = {"A": "02346758", "B": "012367894", "C": "012378429"}

print(f"List c is {c} and list d is {d}")
print("length of b is ", len(d))  # use comma in-between

List c is ['str', 1, 2, 3, 4] and list d is [0, 1, 'c']
length of b is  3


## คำสั่ง If  
แสดงตัวอย่างการใช้คำสั่ง `if`, `elif`, และ `else` เพื่อควบคุมทิศทางการทำงานของโปรแกรมตามเงื่อนไขที่กำหนด

ด้านล่างจะเป็นตัวอย่างของการตัดเกรด

In [2]:
if 5 > 2:
    print("Five is greater than two!")
    
point = 100
print("point is:", point)

if point >= 80:
    print("Grade A")
elif point >= 70:
    print("Grade B")
else:
    print("Lower than B")

Five is greater than two!
point is: 100
Grade A


## Loop
- `range(n)` => จะให้ผลลัพธ์เป็น iterator ที่มีค่า 0 ถึง n-1 จากนั้นเราสามารถใช้ for each loop ได้<br>
- `print()` ปกติแล้วจะ print แบบขึ้นบรรทัดใหม่เสมอ แต่เราสามารถบังคับให้ไม่ขึ้นได้โดยการกำหนด `end=""` <br>
- `enumerate()` ใช้ในการวนลูปผ่านรายการ (list) พร้อมกับให้ค่า **ลำดับดัชนี (index)** และ **ค่าของสมาชิก** ในแต่ละรอบของลูป  
เช่น `enumerate(c)` จะให้ทั้งลำดับของสมาชิกใน `c` และค่าของสมาชิกนั้นในแต่ละรอบ

In [3]:
for i in range(5):
    print(i)

# for i in range(5):
#     print(i, end=" ")
print("-----------------")

c = ["str", 1, 2, 3, 4]
for n, value in enumerate(c):
    print(f"n: {n}, value: {value}")

0
1
2
3
4
-----------------
n: 0, value: str
n: 1, value: 1
n: 2, value: 2
n: 3, value: 3
n: 4, value: 4


## Function
รูปแบบของฟังก์ชันในภาษา Python:

```python
def ชื่อฟังก์ชัน(พารามิเตอร์):
    # คำสั่งที่ต้องการให้ทำงาน
    return ค่าที่ส่งกลับ #*(ถ้ามี)*


In [4]:
# แบบไม่คืนค่า
def printDash():
    print("------------")
print("Defining a function")

Defining a function


In [5]:
# แบบคืนค่า
def isEven(num):
    if num % 2 == 0:
        return True
    else:
        return False

print(isEven(3))

False


## การเข้าถึงข้อมูลใน Dictionary และการวนลูป  
- แสดงค่าทั้งหมดใน dictionary ด้วย `print()` 
    - ตัวแปร `contact` เคยประกาศไว้ตั้งแต่[ตรงนี้](#Variable) cell ไหนเคยรันไว้จะมีผลต่อ cell ด้านล่างด้วย
- เข้าถึงค่าสมาชิกแบบระบุคีย์ เช่น `contact["C"]`
- เพิ่มสมาชิกใหม่เข้าไปใน dictionary
- วนลูปผ่าน `keys()` เพื่อแสดงชื่อและเบอร์โทร
    - `keys()` เป็นคำสั่งที่ช่วยดึง keys ทั้งหมดใน dict ออกมา
- ใช้ `enumerate()` เพื่อแสดงลำดับของคีย์ใน dictionary

In [6]:
print(contact)
print(contact["C"])

contact[99] = "012379845"
for k in contact.keys():
    print("name:", k, "phone:", contact[k])

for k in contact.keys():
    print("key:", k)
printDash()
for n, k in enumerate(contact.keys()):
    print(f"n: {n} key:", k)

{'A': '02346758', 'B': '012367894', 'C': '012378429'}
012378429
name: A phone: 02346758
name: B phone: 012367894
name: C phone: 012378429
name: 99 phone: 012379845
key: A
key: B
key: C
key: 99
------------
n: 0 key: A
n: 1 key: B
n: 2 key: C
n: 3 key: 99


## List & Tuple operations

- สร้างลิสต์ (`list`) และทูเพิล (`tuple`) ที่มี datatype หลายประเภท
- เข้าถึงสมาชิกในแต่ละตำแหน่งด้วย index
- เรียก printDash() ที่ประกาศไว้ตั้งแต่[ตรงนี้](#Function)
- ใช้ `len()` เพื่อหาความยาว
- ใช้เมธอด `.remove()` เพื่อลบ และ `.append()` เพื่อต่อท้ายกับลิสต์
- เปรียบเทียบประเภทข้อมูลด้วย `type()`
- แสดงให้เห็นว่า tuple ไม่สามารถเพิ่มหรือลบสมาชิกได้ (บรรทัดที่ถูกคอมเมนต์ไว้จะ error ถ้าเปิดใช้งาน)


In [7]:
# List of >2 data types
ls = [1, 2, 0.1, "apple", True]
tup = (4, 5)

print(ls)
print(tup)
print(ls[3])  # Output: apple
print(tup[0])  # Output: 4
printDash()

print(f"length ls is {len(ls)}")
print(f"length ls is {len(tup)}")
ls.remove(2)
print(f"length ls is {len(ls)}: {ls} -> removed {2}")
ls.append(10)
print(f"length ls is {len(ls)}: {ls}")
print(type(ls))
printDash()
print(f"length tup is {len(tup)}")
print(type(tup))
# print(tup.append(2)) # ระเบิด
# print(tup.remove(2)) # ระเบิด

[1, 2, 0.1, 'apple', True]
(4, 5)
apple
4
------------
length ls is 5
length ls is 2
length ls is 4: [1, 0.1, 'apple', True] -> removed 2
length ls is 5: [1, 0.1, 'apple', True, 10]
<class 'list'>
------------
length tup is 2
<class 'tuple'>


## Objected-Oriented Programming

**แนวคิดแบบอ้างอิง (Reference)**
- การกำหนด `M = L[3]` ไม่ได้สร้างสำเนาใหม่ แต่ให้ `M` ชี้ไปยังลิสต์เดียวกับ `L[3]`
- การเปลี่ยนแปลงค่าใน `M` จะกระทบ `L[3]` ด้วย เพราะทั้งคู่อ้างอิงข้อมูลเดียวกัน
- ตัวแปร `name` ไม่ได้รับผลกระทบจากการเปลี่ยนค่าภายหลังใน `M` เพราะเป็นการเก็บค่าลงลิสต์ ไม่ได้เชื่อมต่อแบบ pointer

แนวคิดนี้เกี่ยวข้องกับ **พฤติกรรมของ object** และ **การจัดการหน่วยความจำ** 

In [8]:
L = [1, 2.1, "Hello", [1, 2, "Sam"]]
name = "Frodo"
M = L[3]  # assign pointer

M[2] = name
print(L[3][2])
M[2] = "Aragon"
print(L[3][2])
print(name)

Frodo
Aragon
Frodo


## Arithmatic operation

ในส่วนนี้นั้นเป็นตัวดำเนินการตัวเลขที่ Python นั้นมีให้ ก็จะเป็นการ บวก ลบ คูณ หาร mod ยกกำลัง

In [9]:
print("Sum", a + b)
print("Differece", a - b)
print("Product", a * b)
print("Mod", a % 3)
print("Square", a**2)

"""
del a  # Deleting value
try:
    print(a)
except:
    print("Error a is not defined")
"""

print(f"c => {c}")
list = c.copy()
list.append("test")
print(list)
printDash()
# list.insert(1,"one")
list.remove(2)
print(f"c => {c}")
print(f"list => {list}")

# Showing type of variable
print(type(c))

Sum 10.1
Differece 9.9
Product 1.0
Mod 1
Square 100
c => ['str', 1, 2, 3, 4]
['str', 1, 2, 3, 4, 'test']
------------
c => ['str', 1, 2, 3, 4]
list => ['str', 1, 3, 4, 'test']
<class 'list'>


## List ซ้อน List  
ใน Python ไม่มีโครงสร้างลิสต์ 2 มิติโดยตรง แต่สามารถจำลองได้ด้วยการเก็บลิสต์ไว้ภายในลิสต์อีกชั้นหนึ่ง  
ตอนนี้ list เป็น `list => ['str', 1, 3, 4, 'test']`
- แก้ไขสมาชิกสุดท้ายของลิสต์ให้เป็นค่าเดียว (`"last"`)
- เปลี่ยนสมาชิกนั้นให้เป็นลิสต์ใหม่ (ซ้อนลิสต์)
- เข้าถึงสมาชิกย่อยในลิสต์ซ้อน เช่น `list[-1][1]`
- ตรวจสอบชนิดข้อมูลด้วย `type()`


In [10]:
list[-1] = "last"
print(list)
list[-1] = ["one", "two", "three"]
print(list)
print(list[-1][1])
print(type(list[-1][1]))

# สร้าง array 2 มิติแบบ list ซ้อน list
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(matrix[1][2])  # เข้าถึงสมาชิกในตำแหน่งแถวที่ 1 คอลัมน์ที่ 2 (index เริ่มที่ 0) Output: 6

print(matrix) # print ตรงๆก็ได้แต่จะไม่ค่อยสวยเพราะจเป็นแถวเดียว จะไม่เหมาะเมื่อเป็น 2D ที่ใหญ่กว่านี้
# วนลูปแสดงค่าทั้ง matrix
for row in matrix:
    print(row)


['str', 1, 3, 4, 'last']
['str', 1, 3, 4, ['one', 'two', 'three']]
two
<class 'str'>
6
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


## 📝 <font color="red">แบบฝึกหัด basic python</font>

ก่อนจะไป Numpy ลองทำแบบฝึกหัดกันเล่นๆทบทวน Python กันก่อนนะครับ

### <font color="red">แบบฝึกหัดที่ 1</font>

**สร้างลิสต์และวนลูป**
1. เขียน list `fruits` ที่มี `["แอปเปิล", "กล้วย", "มะม่วง"]` เป็นสมาชิก
2. ใช้ `enumerate()` และ loop เพื่อพิมพ์ผลลัพธ์ดัง output ด้านล่าง
3. ใช้ if เพื่อดักเมื่อเจอ `"มะม่วง"` ให้พิมพ์ `"แมงโก้!"`
```python
output:

1 แอปเปิล
2 กล้วย
3 แมงโก้!

In [11]:
## คำตอบแบบฝึกหัดที่ 1

fruits = ["Apple" , "Banana" , "Mango"]
for k, v in enumerate(fruits):
    if(v == "Mango"):
        print("Mango!!")
        continue
    print(v)
   

Apple
Banana
Mango!!


### <font color="red">แบบฝึกหัดที่ 2</font>
1. เขียนตัวแปรประเภท dictionary ที่มี key และ value เป็น `{"ชายเหมี่ยง": "เชียงใหม่", "ชายเรียง": "เชียงราย", "ชายสี่": "หมี่เกี๊ยว!!"}`
2. ใช้ loop กับฟังก์ชัน `keys()` เพื่อพิมพ์มุกแต่ละตับออกมาให้อยู่ในรูปแบบดั่ง output
3. เพิ่มตับสุดท้ายเข้าไปว่า `"ชายน้อย"` ตอบเป็น `"พะ พี่ พจ จะ มะ มาน"` โดยการเรียก `gags["ชายน้อย"] = ...`
4. จากนั้นทำข้อ 2 อีกรอบ

```python
output:

ชายเหมี่ยง =>  เชียงใหม่
ชายเรียง =>  เชียงราย
ชายสี่ =>  หมี่เกี๊ยว!!
แฮร่!!!....
---------------
ชายเหมี่ยง =>  เชียงใหม่
ชายเรียง =>  เชียงราย
ชายสี่ =>  หมี่เกี๊ยว!!
ชายน้อย =>  พะ พี่ พจ จะ มะ มาน
เฉียบบบบ!!

In [12]:
## คำตอบแบบฝึกหัดที่ 2
gags = {"ชายเมี่ยง" : "เชี่ยงใหม่", "ชายเรียง" : "เชียงราย", "ชายสี่" : "หมี่เกี๊ยว"}
for key in gags.keys():
    print(key)
print("แฮร่!!!....")
print("__________")
gags["ชายน้อย"] = "พะ พี่ พจ จะ มะ มาน"
for key in gags.keys():
    print(key)
print("เฉียบบบบ!!")

ชายเมี่ยง
ชายเรียง
ชายสี่
แฮร่!!!....
__________
ชายเมี่ยง
ชายเรียง
ชายสี่
ชายน้อย
เฉียบบบบ!!


## Numpy 

- สร้าง array แบบ 1 มิติ (`arr1d`)
- ใช้ `len()` เพื่อนับจำนวนสมาชิก
- Slice ข้อมูลบางส่วน เช่น `arr1d[0 : len(arr1d)]`
- ใช้ `[::-1]` เพื่อเรียงลำดับจากหลังมาหน้า
- คำนวณค่าเฉลี่ย (`mean`) และหาค่ามากที่สุด (`max`)
- สร้าง array ใหม่อีกอัน (`arr1d_2`) เพื่อใช้เปรียบเทียบกับ `arr1d` แบบตัวต่อตัว (element-wise)
- ใช้ `np.abs()` เพื่อหาค่าสัมบูรณ์
- คำนวณค่าต่างของ array (`arr1d - arr1d_2`) เพื่อให้ได้ array ใหม่ (`arr1d_3`)arr

In [13]:
import numpy as np

arr1d = np.array([1, 10, 3, 4, 12, -5])
# arr1d = np.array([1, 10, 3.0, 4, 12, -5])
print(len(arr1d))
printDash()
print(arr1d[0 : len(arr1d)])  # 1, 2
print(arr1d[::-1])
print(arr1d.mean())
print(arr1d.max())
printDash()
arr1d = np.array([1, 10, 3, 4, 12, -5])
arr1d_2 = np.array([7, 4, 2, 6, 14, -10])
print(arr1d_2 > arr1d)
print(arr1d_2 < arr1d)
print(np.abs(arr1d_2))

# arr1d_3 = arr1d + arr1d_2
arr1d_3 = arr1d - arr1d_2
# arr1d_3 = arr1d * arr1d_2
print(arr1d_3)

6
------------
[ 1 10  3  4 12 -5]
[-5 12  4  3 10  1]
4.166666666666667
12
------------
[ True False False  True  True False]
[False  True  True False False  True]
[ 7  4  2  6 14 10]
[-6  6  1 -2 -2  5]


### Array2D
- `arr2d_1`, `arr2d_2`, และ `arr2d_3` เป็น array 2 มิติขนาด 2x3
- ถ้าใน array มีค่า float เช่น `2.0` จะทำให้ทั้ง array ถูกแปลงเป็น `float64` โดยอัตโนมัติ
- ถ้าต้องการระบุชนิดข้อมูลเอง เช่น `float32`, ให้ใช้ `dtype=np.float32` เช่น `arr2d_3`

### Array 4 มิติ
- สร้าง array ขนาด 4 มิติ (3 block, 1 ช่อง, 2 แถว, 3 คอลัมน์)
- ใช้ ndim เพื่อตรวจสอบจำนวนมิติของ array

In [14]:
arr2d_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2d_2 = np.array([[1, 2.0, 3], [4, 5, 6]])
arr2d_3 = np.array([[1, 2.0, 3], [4, 5, 6]], dtype=np.float32)
zeros = np.zeros([2, 3], dtype=np.int32)
ones = np.ones([2, 3], dtype=np.float64)

print(arr2d_1)
print(arr2d_2)
print("arr2d_2 =>", arr2d_2.dtype)
print("arr2d_3 =>", arr2d_3.dtype)
printDash()
print(">เปลี่ยน dtype ของ arr2d_2")
arr2d_2 = arr2d_2.astype(np.float32)
print("arr2d_2 =>", arr2d_2.dtype)

printDash()
ones4d = np.ones([3,1, 2, 3], dtype=np.float64)
print(ones4d)
print(ones4d.dtype)
print(ones4d.ndim)
printDash()

arr2d_1 = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
for a in arr2d_1:
    print(a)
# สังเกตุวงเล็บดีๆ ผลลัพธ์ที่ออกมานั้นเป็นลิสซ้อนลิส ไม่ใช่ ลิส2มิติ


focus_2d = arr2d_2
for i in range(len(focus_2d)):
    for j in range(len(focus_2d[i])):
        print(focus_2d[i][j])

print(focus_2d.shape)
row, col = focus_2d.shape
for j in range(col):
    for i in range(row):
        print(focus_2d[i][j], end=" ")
    print()

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
arr2d_2 => float64
arr2d_3 => float32
------------
>เปลี่ยน dtype ของ arr2d_2
arr2d_2 => float32
------------
[[[[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]]]
float64
4
------------
[1 2 3]
[4 5 6]
[7 8 9]
1.0
2.0
3.0
4.0
5.0
6.0
(2, 3)
1.0 4.0 
2.0 5.0 
3.0 6.0 


### Array shape
- `flatten()` เพื่อแปลง array 2 มิติให้เป็น 1 มิติ
- `reshape()` เพื่อเปลี่ยนขนาด array เป็นรูปแบบใหม่ โดยยังคงข้อมูลเดิมไว้

In [ ]:
focus_2d = np.array([[1, 2.0, 3], [4, 5, 6]])
print(focus_2d.shape())
printDash()
print(focus_2d.flatten())
# (2, 3)
print(focus_2d.reshape(focus_2d.shape[1], focus_2d.shape[0]))
print(focus_2d.reshape(1, 6))
print(focus_2d.reshape(6, 1))
print("size is ", focus_2d.size)
printDash()
print("แต่ Array จริงๆไม่มีการเปลี่ยนแปลงใดๆ")
print(focus_2d)

### Array2D with Slicing
- `np.arange(1, 31)` → สร้าง array จาก 1 ถึง 30
- `.reshape(5, 6)` → เปลี่ยนให้เป็น array 2 มิติขนาด 5 แถว 6 คอลัมน์ (คูณแล้วได้ 30)
- `.resize(3, 10)` → เปลี่ยนให้เป็น array 2 มิติขนาด 3 แถว 10 คอลัมน์ (คูณแล้วได้ 30) **<font color="red">กระทบตัวแปร Q ทันที</font>** ไม่มีการเขียนทับ
- ทำ Slicing เลือก แถวที่ 1 ถึง 3 (`[1:4]`) และ คอลัมน์ที่ 2 ถึง 5 (`[2:6]`)
    - แต่มีแค่แถว 0 ถึง 2 ทำให้ผลลัพธ์ออกมา 2 แถว

In [ ]:
Q = np.arange(1, 31)
print("> ตอนนี้รูปร่าง 1x30")
print(Q)
print("> ปรับรูปร่างให้เป็น 5x6")
# Q = np.array([[ 1,  2  ,3 , 4 , 5 , 6],
#              [ 7 ,  8 , 9 ,10 ,11 ,12],
#              [13,  14 ,15 ,16 ,17 ,18],
#              [19,  20 ,21 ,22 ,23 ,24],
#              [25,  26 ,27 ,28 ,29 ,30]])
Q = Q.reshape(5,6)
print(Q)
printDash()
print("> ปรับรูปร่างให้เป็น 3x10")
Q.resize(3, 10) # เปลี่ยนแปลงตัวแปร Q ทันที
print(Q)
printDash()
print("> slicing แถวที่ 1 ถึง 3 [1:4] และ คอลัมน์ที่ 2 ถึง 5 [2:6]")
print(Q[1:4,2:6])
print(Q[0:100])

### ข้อควรระวังการ slicing
-  คำสั่ง `Q[1:4][0:2]` จะไม่เหมือน `Q[1:4, 0:2]`
-  `Q[1:4][0:2]` → จะทำงานแบบ chained indexing

In [ ]:
Q = Q.reshape(5,6)
print(Q)
print("> คำสั่ง Q[1:4]")
print(Q[1:4])
printDash()
print("> คำสั่ง Q[1:4, 0:2]")
print(Q[1:4, 0:2])
printDash()
print("> คำสั่ง Q[1:4][0:2]")
print(Q[1:4][0:2])
printDash()

In [ ]:
# Create a 2D array
arr = np.array([[1, 2], [3, 4]])
print("Original array:")
print(arr)

# Append a row [5, 6]
arr = np.append(arr, [[5, 6]], axis=0)
print("Appended row:")
print(arr)

# Append a column [7, 8, 9]
arr = np.append(arr, [[7], [8], [9]], axis=1)
print("Appended column:")
print(arr)

# arr[:,0]
# arr[:,:1]
# arr[:, 0:1]
arr[1:,1:]
arr[1:3,1:3]

In [ ]:
# Expand dimensions along axis 0 (add a new row)
expanded_row = np.expand_dims(arr, axis=0)
print("Expanded along axis 0 (new row):")
print(expanded_row)
print(expanded_row.shape)
print(expanded_row.ndim)

# Expand dimensions along axis 1 (add a new column)
expanded_column = np.expand_dims(arr, axis=1)
# print("Expanded along axis 1 (new column):")
print(expanded_column)
print(expanded_column.shape)
print(expanded_column.ndim)

## 📝 <font color="red">แบบฝึกหัด basic numpy</font>

### <font color="red">แบบฝึกหัด 3</font>

**สำรวจชนิดข้อมูลและมิติของ Array**

1. สร้าง array2d ชื่อ `A` ขนาด 2x3 โดยให้มีทั้งจำนวนเต็มและทศนิยม ด้านในเป็นค่าเท่าไหร่ก็ได้
    - จะประกาศด้วย arange() หรือ ใช้ = `[ ., ., .]` ก็ได้
3. ตรวจสอบชนิดข้อมูล (`dtype`) ของ `A`
4. แปลง `A` ให้เป็น `float32` โดยใช้ `astype()` พร้อมพิมพ์ `dtype` ออกมาเช็ค
5. สร้าง array4d ชื่อ `B` ขนาด 3×1×2×3 ที่มีแต่ค่า 1 (`np.ones`) และระบุให้เป็น `float64`
6. แสดงจำนวนมิติของ `B` และชนิดข้อมูลของมัน

In [34]:
arr = np.arange(1,7)
arr = arr.reshape(2,3)
print(arr)
print(type(arr))

arr = arr.astype(np.float32)
print(arr.dtype)

B = np.ones([3,1,2,3],dtype = np.float32)
print(B)
print(B.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
float32
[[[[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]]]
float32
